### ISSUE TITLE
Dictionary imports error seemingly randomly

### ISSUE THREAD

**Issue by Ceynou** [themoeway/yomitan#768]
**Description**
`Error: Unexpected response of type undefined ({"action":"optionsGetFull"})`
I can refresh the page and retry and it seems to work but then it errors again.

```
AbortError: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved 5 ConduitsParent.sys.mjs:362
Promise resolved while context is inactive
web-extension.js:71
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
web-extension.js:71
WebExtension context not found! ExtensionParent.sys.mjs:1285
AbortError: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved 2 ConduitsParent.sys.mjs:362
Yomitan (development build) 24.2.26.0 has encountered a problem.
Originating URL: moz-extension://2036230e-8593-4e95-b4c6-e05ff424cad0/settings.html#!profile
Error: Unexpected response of type undefined ({"action":"optionsGetFull"})
_invoke/</<@moz-extension://2036230e-8593-4e95-b4c6-e05ff424cad0/js/comm/api.js:390:32

Issues can be reported at https://github.com/themoeway/yomitan/issues log.js:138:35
Uncaught (in promise) Error: Unexpected response of type undefined ({"action":"triggerDatabaseUpdated","params":{"type":"dictionary","cause":"import"}})
    _invoke moz-extension://2036230e-8593-4e95-b4c6-e05ff424cad0/js/comm/api.js:390
api.js:390:32
Yomitan (development build) 24.2.26.0 has encountered a problem.
Originating URL: moz-extension://2036230e-8593-4e95-b4c6-e05ff424cad0/settings.html#!profile
Error: Unexpected response of type undefined ({"action":"optionsGetFull"})
_invoke/</<@moz-extension://2036230e-8593-4e95-b4c6-e05ff424cad0/js/comm/api.js:390:32

Issues can be reported at https://github.com/themoeway/yomitan/issues log.js:138:35
```

**Browser version**
115.8.0esr (64-bit)

**Yomitan version**
Yomitan (development build) 24.2.26.0

Tried on a fresh  install, all the permissions were given

**Comment by stephenmk** [comment]
See #723

**Comment by StefanVukovic99** [comment]
Closing duplicate
